disabled_rules: # rule identifiers to exclude from running
- line_length
- nesting
excluded:
  - External
  - Carthage
  - XCode Templates
  - .build
opt_in_rules:
  - vertical_whitespace

# reporter type (xcode, json, csv, checkstyle, junit, html, emoji)
reporter: "xcode"
